# Generated by Django 3.2.7 on 2021-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_score', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('time_in_bed', models.IntegerField()),
                ('efficency', models.IntegerField()),
                ('restfulness', models.IntegerField()),
                ('rem', models.IntegerField()),
                ('deep', models.IntegerField()),
                ('light', models.IntegerField()),
                ('latency', models.IntegerField()),
                ('heartrate', models.FloatField()),
            ],
        ),
    ]
