# Generated by Django 3.2.7 on 2021-09-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_score', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('score_meet_daily_targets', models.IntegerField()),
                ('score_recovery_time', models.IntegerField()),
                ('score_training_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='readiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.IntegerField()),
            ],
        ),
    ]
