# Generated by Django 3.2.7 on 2021-09-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activity_readiness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activity',
        ),
        migrations.DeleteModel(
            name='readiness',
        ),
        migrations.DeleteModel(
            name='sleep',
        ),
    ]
