# Generated by Django 3.2.7 on 2021-09-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20210915_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('activity_score', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('score_meet_daily_targets', models.IntegerField()),
                ('score_recovery_time', models.IntegerField()),
                ('score_training_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='readiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('readiness_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('sleep_score', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('time_in_bed', models.IntegerField()),
                ('efficency', models.IntegerField()),
                ('restfulness', models.IntegerField()),
                ('rem', models.IntegerField()),
                ('deep', models.IntegerField()),
                ('light', models.IntegerField()),
                ('latency', models.IntegerField()),
                ('heartrate', models.FloatField()),
            ],
        ),
    ]
