# Generated by Django 3.2.7 on 2021-09-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_activity_readiness_sleep'),
    ]

    operations = [
        migrations.CreateModel(
            name='air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('co2', models.IntegerField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
            ],
        ),
    ]
